os:
  - Visual Studio 2022

platform:
  - x64
  - x86
  
branches:
  only:
    - master

configuration:
  - Release
  
build:
  verbosity: detailed
  
environment:
  projName: $(APPVEYOR_PROJECT_SLUG)
  buildPlatform: $(PLATFORM)
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(PLATFORM)
  
install:
  - cd ..
  - curl -fsS -o pin.zip https://software.intel.com/sites/landingpage/pintool/downloads/pin-external-3.31-98861-g71afcc22f-msvc-windows.zip
  - 7z x pin.zip
  - cd pin-external-3.31-98861-g71afcc22f-msvc-windows
  - cd source
  - cd tools
  - cp -r ../../../%projName% ./
  - cd %projName%
 
build_script:
  - ps: $PlatformToolset = "v143"
  - ps: (Get-Content TinyTracer.vcxproj) | %{$_ -replace "v110", $PlatformToolset} | Set-Content TinyTracer.vcxproj
  - ps: msbuild TinyTracer.vcxproj "/p:platform=$env:platform;configuration=$env:configuration"
  
after_build:
  - mkdir C:\projects\%projName%\install32_64\%artifactName%
  - if [%buildPlatform%]==[x64] ( cp x64\Release\TinyTracer.dll C:\projects\%projName%\install32_64\%artifactName%\TinyTracer64.dll )
  - if [%buildPlatform%]==[x86] ( cp Release\TinyTracer.dll C:\projects\%projName%\install32_64\%artifactName%\TinyTracer32.dll )
 
artifacts:
  - path: install32_64\%artifactName%
  
